/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gnosis;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import util.ClaseFile;
import util.Escribir;
import util.Leer;

/**
 *
 * @author GHCM-T430-01
 */
public class GeneradorScripts extends javax.swing.JFrame {
        String nameCon, papelera;
        String nameApps ,Passw,cadenaBaseDown;
        String texto="";
        String sPath="";
    /**
     * Creates new form GeneradorScripts
     */
    public GeneradorScripts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        lblNameConc = new javax.swing.JLabel();
        txtNameConc = new javax.swing.JTextField();
        lblAppsSch = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        lblUpload = new javax.swing.JLabel();
        txtUploadConc = new javax.swing.JTextField();
        btnGrarConc = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtDownload = new javax.swing.JTextField();
        lblDonw = new javax.swing.JLabel();
        txtAppsSch = new javax.swing.JTextField();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblPlnt = new javax.swing.JLabel();
        txtTmloc = new javax.swing.JTextField();
        lblShort = new javax.swing.JLabel();
        txtShort = new javax.swing.JTextField();
        txtLng = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtApp = new javax.swing.JTextField();
        lblApp = new javax.swing.JLabel();
        lblUsr = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtUsr = new javax.swing.JTextPane();
        lblPsw = new javax.swing.JLabel();
        txtPsw = new javax.swing.JTextField();
        lblHost = new javax.swing.JLabel();
        txtHost = new javax.swing.JTextField();
        lblPort = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        lblSid = new javax.swing.JLabel();
        txtSid = new javax.swing.JTextField();
        lblUpl = new javax.swing.JLabel();
        lblDwn = new javax.swing.JLabel();
        txtUpl = new javax.swing.JTextField();
        txtDwn = new javax.swing.JTextField();
        btnUplTem = new javax.swing.JButton();
        btnDnwlTem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        lblUsrDD = new javax.swing.JLabel();
        txtNameApps = new javax.swing.JTextField();
        lblRuta = new javax.swing.JLabel();
        txtRuta = new javax.swing.JTextField();
        lblPswDD = new javax.swing.JLabel();
        txtPassW = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNameConcur = new javax.swing.JTextField();
        lblNameApl = new javax.swing.JLabel();
        txtNameApl = new javax.swing.JTextField();
        lblD = new javax.swing.JLabel();
        txtCadenaD = new javax.swing.JTextField();
        btnGD = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCadenaU = new javax.swing.JTextField();
        btnU = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jInternalFrame4 = new javax.swing.JInternalFrame();
        lblShort1 = new javax.swing.JLabel();
        txtShortName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtUsr1 = new javax.swing.JTextPane();
        lblUsr1 = new javax.swing.JLabel();
        lblPsw1 = new javax.swing.JLabel();
        txtPsw1 = new javax.swing.JTextField();
        lblRequestGroup = new javax.swing.JLabel();
        txtReqGroup = new javax.swing.JTextField();
        txtXbol = new javax.swing.JTextField();
        lblNameApl1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtModAppShorN = new javax.swing.JTextField();
        lblUpl1 = new javax.swing.JLabel();
        lblDwn1 = new javax.swing.JLabel();
        txtDwn1 = new javax.swing.JTextField();
        btnUplTem1 = new javax.swing.JButton();
        btnDnwlTem1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtUP = new javax.swing.JTextField();
        jInternalFrame5 = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        jInternalFrame6 = new javax.swing.JInternalFrame();
        jLabel10 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPssw = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNameL = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtAppSh = new javax.swing.JTextField();
        txtUpload = new javax.swing.JTextField();
        txtDown = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnUpload = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jInternalFrame7 = new javax.swing.JInternalFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMainPane = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtReemp = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtOrig = new javax.swing.JTextField();
        btnGrabar = new javax.swing.JButton();
        txtL = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jInternalFrame8 = new javax.swing.JInternalFrame();
        jLabel23 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtScr = new javax.swing.JTextArea();
        txtPath = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtPgs = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jInternalFrame1.setVisible(true);

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Concurrentes");

        lblNameConc.setText("Nombre Concurrente:");

        txtNameConc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameConcActionPerformed(evt);
            }
        });

        lblAppsSch.setText("Usuario schema apps:");

        lblPass.setText("Contraseña:");

        lblUpload.setText("UPLOAD:");

        txtUploadConc.setName(""); // NOI18N
        txtUploadConc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUploadConcActionPerformed(evt);
            }
        });

        btnGrarConc.setText("Generar/Copiar");
        btnGrarConc.setName("btnGenerar"); // NOI18N
        btnGrarConc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrarConcActionPerformed(evt);
            }
        });

        jButton1.setText("Generar/Copiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblDonw.setText("DOWNLOAD: ");

        txtAppsSch.setText("apps");
        txtAppsSch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAppsSchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNameConc)
                            .addComponent(lblAppsSch, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNameConc, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAppsSch, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPass)
                                .addComponent(lblUpload))
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(txtUploadConc, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGrarConc))
                                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                            .addComponent(lblDonw)
                            .addGap(16, 16, 16)
                            .addComponent(txtDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameConc)
                    .addComponent(txtNameConc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAppsSch)
                    .addComponent(txtAppsSch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUpload)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtUploadConc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGrarConc)))
                .addGap(11, 11, 11)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDonw)
                    .addComponent(txtDownload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(283, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Concurrentes", jInternalFrame1);

        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        lblPlnt.setText("Ruta plantilla (Subida):");

        txtTmloc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTmlocActionPerformed(evt);
            }
        });

        lblShort.setText("Shortname Concurrente:");

        txtShort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShortActionPerformed(evt);
            }
        });

        jLabel5.setText("Lenguaje:");

        txtApp.setText("XBOL");

        lblApp.setText("Shortname Aplicación:");

        lblUsr.setText("Usuario:");

        txtUsr.setText("apps");
        jScrollPane1.setViewportView(txtUsr);

        lblPsw.setText("Contraseña:");

        txtPsw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPswActionPerformed(evt);
            }
        });

        lblHost.setText("Host:");

        lblPort.setText("Puerto:");

        lblSid.setText("SID:");

        lblUpl.setText("UPLOAD:");

        lblDwn.setText("DOWNLOAD:");

        txtDwn.setToolTipText("");
        txtDwn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDwnActionPerformed(evt);
            }
        });

        btnUplTem.setText("Generar/Copiar");
        btnUplTem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUplTemActionPerformed(evt);
            }
        });

        btnDnwlTem.setText("Generar/Copiar");
        btnDnwlTem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDnwlTemActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Plantillas");

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addComponent(lblPlnt)
                .addGap(18, 18, 18)
                .addComponent(txtTmloc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblShort)
                .addGap(18, 18, 18)
                .addComponent(txtShort))
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(lblApp)
                        .addGap(18, 18, 18)
                        .addComponent(txtApp, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtLng, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(lblUsr)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(lblPsw)
                        .addGap(18, 18, 18)
                        .addComponent(txtPsw, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(lblHost)
                        .addGap(18, 18, 18)
                        .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(lblPort)
                        .addGap(18, 18, 18)
                        .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(lblSid)
                        .addGap(18, 18, 18)
                        .addComponent(txtSid, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(lblUpl)
                        .addGap(18, 18, 18)
                        .addComponent(txtUpl, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUplTem))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(lblDwn)
                        .addGap(18, 18, 18)
                        .addComponent(txtDwn, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDnwlTem)))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlnt)
                    .addComponent(txtTmloc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblShort)
                    .addComponent(txtShort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApp)
                    .addComponent(txtApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtLng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsr)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPsw)
                    .addComponent(txtPsw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHost)
                    .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPort)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSid)
                    .addComponent(txtSid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpl)
                    .addComponent(txtUpl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUplTem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDwn)
                        .addComponent(txtDwn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDnwlTem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Plantillas", jInternalFrame2);

        jInternalFrame3.setTitle("Definicion de Datos");
        jInternalFrame3.setVisible(true);

        lblUsrDD.setText("Usuario: ");

        txtNameApps.setText("apps");
        txtNameApps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameAppsActionPerformed(evt);
            }
        });

        lblRuta.setText("Ruta (UPLOAD):");

        lblPswDD.setText("Contraseña:");

        jLabel6.setText("Shortname concurrente:");

        lblNameApl.setText("Shortname de la aplicación:");

        txtNameApl.setText("XBOL");
        txtNameApl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameAplActionPerformed(evt);
            }
        });

        lblD.setText("DOWNLOAD:");

        txtCadenaD.setToolTipText("");

        btnGD.setText("Generar/Copiar");
        btnGD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGDActionPerformed(evt);
            }
        });

        jLabel7.setText("UPLOAD:");

        btnU.setText("Generar/Copiar");
        btnU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Definiciones de datos");

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addComponent(lblUsrDD)
                        .addGap(18, 18, 18)
                        .addComponent(txtNameApps, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(lblRuta)
                        .addGap(31, 31, 31)
                        .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtNameConcur, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addComponent(lblPswDD)
                        .addGap(18, 18, 18)
                        .addComponent(txtPassW, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addComponent(lblNameApl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNameApl, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                .addComponent(lblD)
                                .addGap(18, 18, 18)
                                .addComponent(txtCadenaD, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtCadenaU, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnU)))
                    .addComponent(jLabel4))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(3, 3, 3)
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsrDD)
                            .addComponent(txtNameApps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRuta)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPswDD)
                    .addComponent(txtPassW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNameConcur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameApl)
                    .addComponent(txtNameApl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblD)
                    .addComponent(txtCadenaD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGD))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCadenaU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnU))
                .addContainerGap(279, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Definicion de datos", jInternalFrame3);

        jInternalFrame4.setTitle("Grupo de Solicitudes");
        jInternalFrame4.setVisible(true);

        lblShort1.setText("Shortname Concurrente");

        txtShortName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShortNameActionPerformed(evt);
            }
        });

        txtUsr1.setText("apps");
        jScrollPane2.setViewportView(txtUsr1);

        lblUsr1.setText("Usuario:");

        lblPsw1.setText("Contraseña:");

        txtPsw1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPsw1ActionPerformed(evt);
            }
        });

        lblRequestGroup.setText("Request Group");

        txtXbol.setText("XBOL");

        lblNameApl1.setText("Shortname de la aplicación:");

        jLabel8.setText("Modulo App ShortName");

        txtModAppShorN.setText("OFA");

        lblUpl1.setText("UPLOAD:");

        lblDwn1.setText("DOWNLOAD:");

        txtDwn1.setToolTipText("");
        txtDwn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDwn1ActionPerformed(evt);
            }
        });

        btnUplTem1.setText("Generar/Copiar");
        btnUplTem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUplTem1ActionPerformed(evt);
            }
        });

        btnDnwlTem1.setText("Generar/Copiar");
        btnDnwlTem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDnwlTem1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Grupo de solicitudes");

        txtUP.setToolTipText("");
        txtUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame4Layout = new javax.swing.GroupLayout(jInternalFrame4.getContentPane());
        jInternalFrame4.getContentPane().setLayout(jInternalFrame4Layout);
        jInternalFrame4Layout.setHorizontalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDwn1)
                            .addComponent(lblUpl1))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDwn1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame4Layout.createSequentialGroup()
                                .addComponent(txtUP, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))
                        .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDnwlTem1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnUplTem1))))
                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                        .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblShort1)
                            .addComponent(lblNameApl1)
                            .addComponent(lblRequestGroup)
                            .addComponent(jLabel8))
                        .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtReqGroup)
                                    .addComponent(txtXbol)
                                    .addComponent(txtModAppShorN, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(txtShortName, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                        .addComponent(lblUsr1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                        .addComponent(lblPsw1)
                        .addGap(18, 18, 18)
                        .addComponent(txtPsw1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jInternalFrame4Layout.setVerticalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtShortName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblShort1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsr1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPsw1)
                    .addComponent(txtPsw1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRequestGroup)
                    .addComponent(txtReqGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtXbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameApl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtModAppShorN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUplTem1)
                    .addComponent(lblUpl1)
                    .addComponent(txtUP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDwn1)
                        .addComponent(txtDwn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDnwlTem1))
                .addContainerGap(199, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Grupo de Solicitudes", jInternalFrame4);

        jInternalFrame5.setTitle("Acerca de");
        jInternalFrame5.setVisible(true);

        jLabel3.setText("Desarrollado por: Ernesto y Julián.");

        javax.swing.GroupLayout jInternalFrame5Layout = new javax.swing.GroupLayout(jInternalFrame5.getContentPane());
        jInternalFrame5.getContentPane().setLayout(jInternalFrame5Layout);
        jInternalFrame5Layout.setHorizontalGroup(
            jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(592, Short.MAX_VALUE))
        );
        jInternalFrame5Layout.setVerticalGroup(
            jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(464, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Acerca de..", jInternalFrame5);

        jInternalFrame6.setVisible(true);

        jLabel10.setText("Usuario: ");

        txtUser.setText("apps");

        jLabel11.setText("Contraseña: ");

        jLabel12.setText("Nombre Look Up");

        jLabel13.setText("App Short Name:");

        txtAppSh.setText("XBOL");

        jLabel14.setText("UPLOAD: ");

        jLabel15.setText("DOWNLOD: ");

        btnUpload.setText("Generar/Copiar");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Generar/Copiar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame6Layout = new javax.swing.GroupLayout(jInternalFrame6.getContentPane());
        jInternalFrame6.getContentPane().setLayout(jInternalFrame6Layout);
        jInternalFrame6Layout.setHorizontalGroup(
            jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame6Layout.createSequentialGroup()
                        .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(28, 28, 28)
                        .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPssw, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrame6Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(txtNameL, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame6Layout.createSequentialGroup()
                        .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAppSh, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUpload, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(txtDown))
                        .addGap(54, 54, 54)
                        .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnUpload)
                            .addComponent(jToggleButton2))))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jInternalFrame6Layout.setVerticalGroup(
            jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(txtPssw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNameL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtAppSh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(btnUpload))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jToggleButton2))
                .addContainerGap(243, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Look Ups", jInternalFrame6);

        jInternalFrame7.setVisible(true);

        txtMainPane.setEnabled(false);
        jScrollPane3.setViewportView(txtMainPane);

        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel16.setText("Cargar");

        jLabel17.setText("Reemplazar:");

        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel18.setText("Original");

        txtOrig.setText("apps.");

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        txtL.setText("0");

        jLabel19.setText("Lineas");

        javax.swing.GroupLayout jInternalFrame7Layout = new javax.swing.GroupLayout(jInternalFrame7.getContentPane());
        jInternalFrame7.getContentPane().setLayout(jInternalFrame7Layout);
        jInternalFrame7Layout.setHorizontalGroup(
            jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame7Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame7Layout.createSequentialGroup()
                        .addComponent(btnGrabar)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame7Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtL)))
                .addContainerGap())
            .addGroup(jInternalFrame7Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(txtOrig)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtReemp, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(22, 22, 22))
        );
        jInternalFrame7Layout.setVerticalGroup(
            jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jButton2)
                        .addComponent(jLabel18)
                        .addComponent(txtOrig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jButton3)
                        .addComponent(txtReemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame7Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnGrabar)
                        .addGap(28, 28, 28)
                        .addGroup(jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Limpia Pkgs", jInternalFrame7);

        jInternalFrame8.setVisible(true);

        jLabel23.setText("Páginas OAF ");

        jButton4.setText("...");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtScr.setColumns(20);
        txtScr.setRows(5);
        jScrollPane4.setViewportView(txtScr);

        jLabel20.setText("Path:");

        jLabel21.setText("Cargar Regiones");

        jLabel22.setText("Cargar Páginas");

        txtPgs.setColumns(20);
        txtPgs.setRows(5);
        jScrollPane5.setViewportView(txtPgs);

        jButton5.setText("Establecer Path");

        jButton6.setText("...");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame8Layout = new javax.swing.GroupLayout(jInternalFrame8.getContentPane());
        jInternalFrame8.getContentPane().setLayout(jInternalFrame8Layout);
        jInternalFrame8Layout.setHorizontalGroup(
            jInternalFrame8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame8Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jInternalFrame8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame8Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame8Layout.createSequentialGroup()
                        .addGroup(jInternalFrame8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22))
                        .addGap(20, 20, 20)
                        .addGroup(jInternalFrame8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame8Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5))
                            .addGroup(jInternalFrame8Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jInternalFrame8Layout.setVerticalGroup(
            jInternalFrame8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame8Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(jInternalFrame8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jLabel21)))
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("OAF", jInternalFrame8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Concurrentes");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAppsSchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAppsSchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppsSchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // DOWNLOAD
        // TODO add your handling code here:
        String mipapelera,passW;
        nameApps = this.txtAppsSch.getText();
        nameCon = this.txtNameConc.getText();
        passW = this.txtPass.getText();
        System.out.println(nameCon);
        System.out.println(nameCon.trim());
        //JOptionPane.showMessageDialog(null,nameCon);
        cadenaBaseDown ="FNDLOAD "+nameApps.trim()+"/"+passW.trim()+" O Y DOWNLOAD $FND_TOP/patch/115/import/afcpprog.lct "+nameCon.trim()+".ldt PROGRAM APPLICATION_SHORT_NAME=\"XBOL\" CONCURRENT_PROGRAM_NAME=\""+nameCon.trim()+"\"";
        this.txtDownload.setText(cadenaBaseDown);
        //clipboard
        mipapelera=cadenaBaseDown; //guardamos el contenido de nuestra variable en una cadena auxiliar
        StringSelection stringSelection = new StringSelection(mipapelera);       //creamos objeto y ejecutampos metodo le pasamos nuestra var auxiliar
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard(); // comunicacion con el sistema operativo
        clpbrd.setContents(stringSelection, null); // metdo del copiado
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGrarConcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrarConcActionPerformed
        // UPLOAD
        String passW;

        nameCon = this.txtNameConc.getText();
        nameApps = this.txtAppsSch.getText();
        passW = this.txtPass.getText();

        String cadenaBase="FNDLOAD "+nameApps.trim()+"/"+passW.trim()+" 0 Y UPLOAD $FND_TOP/patch/115/import/afcpprog.lct "+nameCon.trim()+".ldt UPLOAD_MODE=REPLACE CUSTOM_MODE=FORCE";
        this.txtUploadConc.setText(cadenaBase);
        //----------
        papelera=cadenaBase; //guardamos el contenido de nuestra variable en una cadena auxiliar
        StringSelection stringSelection = new StringSelection(papelera);       //creamos objeto y ejecutampos metodo le pasamos nuestra var auxiliar
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard(); // comunicacion con el sistema operativo
        clpbrd.setContents(stringSelection, null); // metdo del copiado
    }//GEN-LAST:event_btnGrarConcActionPerformed

    private void txtUploadConcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUploadConcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUploadConcActionPerformed

    private void txtNameConcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameConcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameConcActionPerformed

    private void txtTmlocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTmlocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTmlocActionPerformed

    private void txtShortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShortActionPerformed

    private void txtPswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPswActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPswActionPerformed

    private void txtDwnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDwnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDwnActionPerformed

    private void btnUplTemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUplTemActionPerformed
        // TODO add your handling code here:
        String cadenaCarga,passW;
        String txtHost,txtPort,txtSid, txtShort,txtApp,txtTmloc;
        papelera = "";
        nameApps = this.txtUsr.getText();
        passW = this.txtPsw.getText();
        txtShort = this.txtTmloc.getText();
        txtTmloc = this.txtTmloc.getText();
        txtHost = this.txtHost.getText();
        txtPort = this.txtPort.getText();
        txtSid = this.txtSid.getText();
        txtApp = this.txtApp.getText();
        String txtLeng = this.txtLng.getText();
        cadenaCarga =    "java oracle.apps.xdo.oa.util.XDOLoader UPLOAD -DB_USERNAME "+nameApps.trim()+" -DB_PASSWORD "+passW.trim()+" -JDBC_CONNECTION \'(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST="+txtHost.trim()+")(PORT="+txtPort.trim()+"))(CONNECT_DATA=(SERVICE_NAME="+txtSid.trim()+")))\' -LOB_TYPE TEMPLATE -LOB_CODE XX_TEMPLATE -XDO_FILE_TYPE RTF -FILE_NAME "+txtTmloc.trim()+" -APPS_SHORT_NAME "+txtApp.trim()+" -NLS_LANG "+txtLeng.trim()+" -TERRITORY MX -LOG_FILE $LOG_FILE_NAME";
        this.txtUpl.setText(cadenaCarga);
        papelera=cadenaCarga;
        StringSelection stringSelection = new StringSelection(papelera);
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
        clpbrd.setContents(stringSelection, null);
    }//GEN-LAST:event_btnUplTemActionPerformed

    private void btnDnwlTemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDnwlTemActionPerformed
        // TODO add your handling code here:
        String cadenaDescarga,passW;
        String txtHost,txtPort,txtSid, txtShort,txtApp,txtTmloc;
        papelera = "";
        nameApps = this.txtUsr.getText();
        passW = this.txtPsw.getText();
        txtShort = this.txtTmloc.getText();
        txtTmloc = this.txtTmloc.getText();
        txtHost = this.txtHost.getText();
        txtPort = this.txtPort.getText();
        txtSid = this.txtSid.getText();
        txtApp = this.txtApp.getText();
        String txtLeng = this.txtLng.getText();
        cadenaDescarga = "java oracle.apps.xdo.oa.util.XDOLoader DOWNLOAD -DB_USERNAME "+nameApps.trim()+" -DB_PASSWORD "+passW.trim()+" -JDBC_CONNECTION \'(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST="+txtHost.trim()+")(PORT="+txtPort.trim()+"))(CONNECT_DATA=(SERVICE_NAME="+txtSid.trim()+")))\' -LOB_TYPE TEMPLATE -LOB_CODE "+txtShort.trim()+" -APPS_SHORT_NAME "+txtApp.trim() +" -LANGUAGE "+txtLeng.trim()+" -lct_FILE $XDO_TOP/patch/115/import/xdotmpl.lct -LOG_FILE $LOG_FILE_NAME";
        this.txtDwn.setText(cadenaDescarga);
        papelera=cadenaDescarga;
        StringSelection stringSelection = new StringSelection(papelera);
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
        clpbrd.setContents(stringSelection, null);
    }//GEN-LAST:event_btnDnwlTemActionPerformed

    private void txtNameAppsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameAppsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameAppsActionPerformed

    private void txtNameAplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameAplActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameAplActionPerformed

    private void btnGDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGDActionPerformed
        // TODO add your handling code here:
        String passW, apl;
        nameCon = this.txtNameConcur.getText();
        nameApps = this.txtNameApps.getText();
        passW = this.txtPassW.getText();
        apl = this.txtNameApl.getText();

        String cadenaBase="FNDLOAD "+nameApps+"/"+passW.trim()+" O Y DOWNLOAD  $XDO_TOP/patch/115/import/xdotmpl.lct "+nameCon.trim()+"_DD.ldt XDO_DS_DEFINITIONS APPLICATION_SHORT_NAME='"+apl.trim()+"' DATA_SOURCE_CODE='"+nameCon.trim()+"' TMPL_APP_SHORT_NAME='"+nameCon.trim()+"' TEMPLATE_CODE='"+nameCon.trim()+"'";

        this.txtCadenaD.setText(cadenaBase);
        //----------
        String papelera2=cadenaBase; //guardamos el contenido de nuestra variable en una cadena auxiliar
        StringSelection stringSelection = new StringSelection(papelera2);       //creamos objeto y ejecutampos metodo le pasamos nuestra var auxiliar
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard(); // comunicacion con el sistema operativo
        clpbrd.setContents(stringSelection, null); // metdo del copiado

    }//GEN-LAST:event_btnGDActionPerformed

    private void btnUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String passW, apl;
        nameCon = this.txtNameConcur.getText();
        nameApps = this.txtNameApps.getText();
        passW = this.txtPassW.getText();
        apl = this.txtNameApl.getText();
        String ruta = this.txtRuta.getText();
        String cadenaBase = "FNDLOAD "+nameApps.trim()+"/"+passW.trim()+" O Y UPLOAD $XDO_TOP/patch/115/import/xdotmpl.lct "+ruta.trim();
        this.txtCadenaU.setText(cadenaBase);
        //----------
        papelera=cadenaBase; //guardamos el contenido de nuestra variable en una cadena auxiliar
        StringSelection stringSelection = new StringSelection(papelera);       //creamos objeto y ejecutampos metodo le pasamos nuestra var auxiliar
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard(); // comunicacion con el sistema operativo
        clpbrd.setContents(stringSelection, null); // metdo del copiado

    }//GEN-LAST:event_btnUActionPerformed

    private void txtShortNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShortNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShortNameActionPerformed

    private void txtPsw1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPsw1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPsw1ActionPerformed

    private void txtDwn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDwn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDwn1ActionPerformed

    private void btnUplTem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUplTem1ActionPerformed
      // TODO add your handling code here:
        String cadenaBase, usuario, contrasenia,shortname, gpo_solicitud, moduloASN, xbol;
        usuario = this.txtUsr1.getText();
        contrasenia = this.txtPsw1.getText();
        gpo_solicitud = this.txtReqGroup.getText();
        moduloASN = this.txtModAppShorN.getText();
        shortname = this.txtShortName.getText();
        xbol =  this.txtXbol.getText();

        cadenaBase= "FNDLOAD "+usuario.trim()+"/"+contrasenia.trim()+" 0 Y UPLOAD $FND_TOP/patch/115/import/afcpreqg.lct "
        + shortname.trim()  +"_RG.ldt "
        + "REQUEST_GROUP REQUEST_GROUP_NAME=\""+gpo_solicitud.trim()+"\" "
        + "APPLICATION_SHORT_NAME=\""+moduloASN+"\" "
        + "REQUEST_GROUP_UNIT UNIT_NAME=\""+shortname.trim()+"\" UNIT_APP=\""+xbol.trim()+"\"";

        this.txtUP.setText(cadenaBase);
        papelera=cadenaBase;
        StringSelection stringSelection = new StringSelection(papelera);
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
        clpbrd.setContents(stringSelection, null);
    }//GEN-LAST:event_btnUplTem1ActionPerformed

    private void btnDnwlTem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDnwlTem1ActionPerformed
        // TODO add your handling code here:
        String cadenaBase, usuario, contrasenia,shortname, gpo_solicitud, moduloASN, xbol;
        usuario = this.txtUsr1.getText();
        contrasenia = this.txtPsw1.getText();
        gpo_solicitud = this.txtReqGroup.getText();
        moduloASN = this.txtModAppShorN.getText();
        shortname = this.txtShortName.getText();
        xbol =  this.txtXbol.getText();

        cadenaBase= "FNDLOAD "+usuario.trim()+"/"+contrasenia.trim()+" 0 Y DOWNLOAD $FND_TOP/patch/115/import/afcpreqg.lct "
        + shortname.trim()  +"_RG.ldt "
        + "REQUEST_GROUP REQUEST_GROUP_NAME=\""+gpo_solicitud.trim()+"\" "
        + "APPLICATION_SHORT_NAME=\""+moduloASN+"\" "
        + "REQUEST_GROUP_UNIT UNIT_NAME=\""+shortname.trim()+"\" UNIT_APP=\""+xbol.trim()+"\"";

        this.txtDwn1.setText(cadenaBase);
        papelera=cadenaBase;
        StringSelection stringSelection = new StringSelection(papelera);
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
        clpbrd.setContents(stringSelection, null);

    }//GEN-LAST:event_btnDnwlTem1ActionPerformed

    private void txtUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUPActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
   // UPLOAD
        String passW;

       String user = this.txtUser.getText().trim();
        String pass = this.txtPssw.getText().trim();
        String nLookUp= this.txtNameL.getText().trim();
        String XBOL = this.txtAppSh.getText().trim();
        

        String cadenaBase = "FNDLOAD "+user+"/"+pass+" O Y UPLOAD $FND_TOP/patch/115/import/aflvmlu.lct "+nLookUp+".ldt FND_LOOKUP_TYPE APPLICATION_SHORT_NAME=\""+XBOL+"\" LOOKUP_TYPE=\""+nLookUp+"\"";
        this.txtUpload.setText(cadenaBase);
        //----------
        papelera=cadenaBase; //guardamos el contenido de nuestra variable en una cadena auxiliar
        StringSelection stringSelection = new StringSelection(papelera);       //creamos objeto y ejecutampos metodo le pasamos nuestra var auxiliar
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard(); // comunicacion con el sistema operativo
        clpbrd.setContents(stringSelection, null); // metdo del copiado


    }//GEN-LAST:event_btnUploadActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
         // UPLOAD
        String passW;

       String user = this.txtUser.getText();
        String pass = this.txtPssw.getText();
        String nLookUp= this.txtNameL.getText();
        String XBOL = this.txtAppSh.getText();
        passW = this.txtPass.getText();

        String cadenaBase = "FNDLOAD "+user+"/"+pass+" O Y DOWNLOAD $FND_TOP/patch/115/import/aflvmlu.lct "+nLookUp+".ldt FND_LOOKUP_TYPE APPLICATION_SHORT_NAME=\""+XBOL+"\" LOOKUP_TYPE=\""+nLookUp+"\"";
        this.txtDown.setText(cadenaBase);
        //----------
        papelera=cadenaBase; //guardamos el contenido de nuestra variable en una cadena auxiliar
        StringSelection stringSelection = new StringSelection(papelera);       //creamos objeto y ejecutampos metodo le pasamos nuestra var auxiliar
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard(); // comunicacion con el sistema operativo
        clpbrd.setContents(stringSelection, null); // metdo del copiado
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    public String eliminarChars(String var,String original,String reemplazo){
        
       var = var.replace(original, reemplazo);
        
        
        return var;
    }
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           // String texto="a caray";
           Integer lineas=0;
            JFileChooser selectorArchivos = new JFileChooser();
            selectorArchivos.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
             int resultado = selectorArchivos.showOpenDialog(this);
               File f =   selectorArchivos.getSelectedFile();
          String nombre = f.getName();
          String path = f.getAbsolutePath();
          sPath=path;
            System.out.println(nombre);
            System.out.println(path);
            System.out.println(resultado);
             
            Leer objL =  new Leer();
                   // TODO add your handling code here:
            texto=objL.LectorArchivo(path); 
            lineas=objL.cuentaLineas(path);
            this.txtL.setText(lineas.toString());
            
            System.out.println("-->"+texto);
            String remp =this.txtReemp.getText().trim();
            String ori = this.txtOrig.getText().trim();
            String strLimpio = eliminarChars(texto,ori,remp);
            this.txtMainPane.setText(texto);
            
            

// indica cual fue la accion de usuario sobre el jfilechooser
           
        
            
         
            
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String remp =this.txtReemp.getText().trim();
            String ori = this.txtOrig.getText().trim();
            
            String strLimpio = eliminarChars(texto,ori,remp);
            texto=texto.toLowerCase();
             strLimpio = eliminarChars(texto,ori,remp);
             texto=texto.toLowerCase();
             strLimpio = eliminarChars(texto,ori,remp);
            
            
            
            
            this.txtMainPane.setText(strLimpio);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        // TODO add your handling code here:
        Escribir objEsc = new Escribir();
        String nCont=this.txtMainPane.getText().trim();
        objEsc.EscribeDoc(sPath,nCont);
        
        
        
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // String texto="a caray";
        ClaseFile cf = new ClaseFile();
       
            JFileChooser selectorArchivos = new JFileChooser();
            selectorArchivos.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
             int resultado = selectorArchivos.showOpenDialog(this);
               File f =   selectorArchivos.getSelectedFile();
          String nombre = f.getName();
          String path = f.getAbsolutePath();
          System.out.println(nombre);
          System.out.println(path);
         String aux1= cf.listFiles(path);
          this.txtScr.setText(aux1);
          this.txtPath.setText(path);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        ClaseFile cf = new ClaseFile();
       
            JFileChooser selectorArchivos = new JFileChooser();
            selectorArchivos.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
             int resultado = selectorArchivos.showOpenDialog(this);
               File f =   selectorArchivos.getSelectedFile();
          String nombre = f.getName();
          String path = f.getAbsolutePath();
          System.out.println(nombre);
          System.out.println(path);
         String aux1= cf.listFiles(path);
          this.txtPgs.setText(aux1);
          //this.txtPath.setText(path);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneradorScripts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneradorScripts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneradorScripts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneradorScripts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneradorScripts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDnwlTem;
    private javax.swing.JButton btnDnwlTem1;
    private javax.swing.JButton btnGD;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnGrarConc;
    private javax.swing.JButton btnU;
    private javax.swing.JButton btnUplTem;
    private javax.swing.JButton btnUplTem1;
    private javax.swing.JToggleButton btnUpload;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JInternalFrame jInternalFrame4;
    private javax.swing.JInternalFrame jInternalFrame5;
    private javax.swing.JInternalFrame jInternalFrame6;
    private javax.swing.JInternalFrame jInternalFrame7;
    private javax.swing.JInternalFrame jInternalFrame8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel lblApp;
    private javax.swing.JLabel lblAppsSch;
    private javax.swing.JLabel lblD;
    private javax.swing.JLabel lblDonw;
    private javax.swing.JLabel lblDwn;
    private javax.swing.JLabel lblDwn1;
    private javax.swing.JLabel lblHost;
    private javax.swing.JLabel lblNameApl;
    private javax.swing.JLabel lblNameApl1;
    private javax.swing.JLabel lblNameConc;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPlnt;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblPsw;
    private javax.swing.JLabel lblPsw1;
    private javax.swing.JLabel lblPswDD;
    private javax.swing.JLabel lblRequestGroup;
    private javax.swing.JLabel lblRuta;
    private javax.swing.JLabel lblShort;
    private javax.swing.JLabel lblShort1;
    private javax.swing.JLabel lblSid;
    private javax.swing.JLabel lblUpl;
    private javax.swing.JLabel lblUpl1;
    private javax.swing.JLabel lblUpload;
    private javax.swing.JLabel lblUsr;
    private javax.swing.JLabel lblUsr1;
    private javax.swing.JLabel lblUsrDD;
    private javax.swing.JTextField txtApp;
    private javax.swing.JTextField txtAppSh;
    private javax.swing.JTextField txtAppsSch;
    private javax.swing.JTextField txtCadenaD;
    private javax.swing.JTextField txtCadenaU;
    private javax.swing.JTextField txtDown;
    private javax.swing.JTextField txtDownload;
    private javax.swing.JTextField txtDwn;
    private javax.swing.JTextField txtDwn1;
    private javax.swing.JTextField txtHost;
    private javax.swing.JTextField txtL;
    private javax.swing.JTextField txtLng;
    private javax.swing.JTextPane txtMainPane;
    private javax.swing.JTextField txtModAppShorN;
    private javax.swing.JTextField txtNameApl;
    private javax.swing.JTextField txtNameApps;
    private javax.swing.JTextField txtNameConc;
    private javax.swing.JTextField txtNameConcur;
    private javax.swing.JTextField txtNameL;
    private javax.swing.JTextField txtOrig;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtPassW;
    private javax.swing.JTextField txtPath;
    private javax.swing.JTextArea txtPgs;
    private javax.swing.JTextField txtPort;
    private javax.swing.JTextField txtPssw;
    private javax.swing.JTextField txtPsw;
    private javax.swing.JTextField txtPsw1;
    private javax.swing.JTextField txtReemp;
    private javax.swing.JTextField txtReqGroup;
    private javax.swing.JTextField txtRuta;
    private javax.swing.JTextArea txtScr;
    private javax.swing.JTextField txtShort;
    private javax.swing.JTextField txtShortName;
    private javax.swing.JTextField txtSid;
    private javax.swing.JTextField txtTmloc;
    private javax.swing.JTextField txtUP;
    private javax.swing.JTextField txtUpl;
    private javax.swing.JTextField txtUpload;
    private javax.swing.JTextField txtUploadConc;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextPane txtUsr;
    private javax.swing.JTextPane txtUsr1;
    private javax.swing.JTextField txtXbol;
    // End of variables declaration//GEN-END:variables
}
